export enum Frequency {
    Daily,
    Monthly,
    Quarterly,
    SemiAnnually,
    Annually,
    OneTime,
    Weekly,
    BiWeekly,
    BiMonthly,
    EveryFourWeeks,
    TwiceMonthly,
    EveryTwoMonths,
    EveryThreeMonths,
}
